application:
  name: accounts
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3307/accounts
    password: MySql20
  liquibase:
    enabled: 'true'
    change-log: classpath:db.changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none

build:
  version: "2.0"

accounts:
  message: "Welcome to the Accounts Service. This is the QA Environment"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371777
