application:
  name: accounts
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/accounts
    password: MySql20
  liquibase:
    enabled: 'true'
    change-log: classpath:db.changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none

build:
  version: "2.0"

accounts:
  message: "Welcome to the Accounts Service. This is the QA Environment"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371777
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8012/

info:
  app:
    name: "loans"
    description: "Eazy Bank loans Application"
    version: "1.0.0"