spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3308/cards
    password: MySql20
  application:
    name: cards
  liquibase:
    enabled: 'true'
    change-log: classpath:db.changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
server:
  servlet:
    context-path: /cards-service
  port: '8090'
build:
  version: "1.0"

cards:
  message: "Welcome to Loans Service Production Yml File "
  contactDetails:
    name: "Welcome Production Environment"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
