spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/cards
    password: MySql20
  application:
    name: cards
  liquibase:
    enabled: 'true'
    change-log: classpath:db.changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
server:
  servlet:
    context-path: /cards-service
  port: '8090'


build:
  version: "1.0"
cards:
  message: "Welcome to Loans Service Local  Yml File "
  contactDetails:
    name: "Welcome  Local  Environment"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8012/

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards  Application"
    version: "1.0.0"
