spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/loans
    password: MySql20
  application:
    name: loans
  liquibase:
    enabled: 'true'
    change-log: classpath:db.changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
server:
  servlet:
    context-path: /loan-service
  port: 8091

build:
  version: "1.0"

loans:
  message: "Welcome to Loans Service Production Yml File "
  contactDetails:
    name: "Welcome Production Environment"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8012/

info:
  app:
    name: "loans"
    description: "Eazy Bank loans Application"
    version: "1.0.0"